In [2]:
import numpy as np

In [96]:
N = 1000
N_1 = 100
N_2 = N - N_1

In [97]:
A = []
B = []
_1 = []
_3 = []
for _ in range(10000):
    X_1 = np.random.standard_normal(N_1)
    X_3 = np.random.standard_normal(N_1)
    X_2 = np.random.standard_normal(N_2)
    X_A = np.concatenate((X_1, X_2))
    X_B = np.concatenate((X_3, X_2))
    S_A = 1./np.cov(X_A)
    S_B = 1./np.cov(X_B)
    #print(S_A, S_B)
    A.append(S_A)
    B.append(S_B)
    S_1 = 1./np.cov(X_1)
    S_3 = 1./np.cov(X_3)
    _1.append(S_1)
    _3.append(S_3)

In [98]:
print(np.cov(A, B))

[[0.00199667 0.00179051]
 [0.00179051 0.00198901]]


In [99]:
print(np.cov(_1, _3))

[[ 2.17235513e-02 -9.55341553e-05]
 [-9.55341553e-05  2.17354952e-02]]


In [12]:
S = np.cov(np.random.multivariate_normal(np.zeros(5), np.eye(5), size = 100).T)

In [13]:
S

array([[ 0.9652614 , -0.04904552, -0.160343  , -0.02955592, -0.01779043],
       [-0.04904552,  0.99356841, -0.01999913, -0.04702477, -0.05634771],
       [-0.160343  , -0.01999913,  0.94647205,  0.04703816, -0.07241305],
       [-0.02955592, -0.04702477,  0.04703816,  0.73444702, -0.02734066],
       [-0.01779043, -0.05634771, -0.07241305, -0.02734066,  1.06041733]])

In [14]:
np.linalg.inv(S)

array([[ 1.07130643,  0.06027152,  0.18360216,  0.03650212,  0.03465461],
       [ 0.06027152,  1.01665681,  0.03284809,  0.06761272,  0.05901992],
       [ 0.18360216,  0.03284809,  1.09721702, -0.05786693,  0.07825974],
       [ 0.03650212,  0.06761272, -0.05786693,  1.3723994 ,  0.03563804],
       [ 0.03465461,  0.05901992,  0.07825974,  0.03563804,  0.95300551]])

In [15]:
np.diag(S)

array([0.9652614 , 0.99356841, 0.94647205, 0.73444702, 1.06041733])

In [16]:
1./np.diag(S)

array([1.0359888 , 1.00647322, 1.05655524, 1.3615686 , 0.94302495])

In [17]:
S = np.cov(np.random.multivariate_normal(np.zeros(2), np.eye(2), size = 100).T)

In [18]:
A = S

In [19]:
A

array([[ 0.95627807, -0.06025651],
       [-0.06025651,  0.94669911]])

In [20]:
np.linalg.eigvals(A)

array([1.01193515, 0.89104203])

In [21]:
B = np.array([[5, 1], [2, 6]])

In [22]:
np.linalg.eigvals(B)

array([4., 7.])

In [23]:
np.linalg.eigvals(A.dot(B))

array([4.05558394, 6.22523153])

In [26]:
import scipy
import scipy.linalg
B_sqrt = scipy.linalg.sqrtm(B)

In [27]:
B_sqrt.dot(A).dot(B_sqrt)

array([[4.69430571, 0.62404362],
       [1.56693475, 5.58650977]])

In [28]:
A.dot(B)

array([[4.66087731, 0.59473898],
       [1.59211565, 5.61993816]])

In [29]:
np.linalg.eigvals(B_sqrt.dot(A).dot(B_sqrt))

array([4.05558394, 6.22523153])

In [31]:
1.01193515 * 7.

7.08354605

In [33]:
scipy.linalg.sqrtm(B)

array([[2.21525044, 0.21525044],
       [0.43050087, 2.43050087]])